apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 --file docker-compose.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: generate
    release-version: 1.0
  name: generate
spec:
#  type: LoadBalancer
  type: NodePort
  ports:
    - name: "8502"
      port: 8502
#      targetPort: 8502
      nodePort: 31798
  selector:
    io.kompose.service: generate
status:
  loadBalancer: {}
